# Generated by Django 3.2.3 on 2021-08-13 13:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210811_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='photos', validators=[main.models.valid_size], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Введите цену в долларах', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена'),
        ),
    ]
